packages:
  - playground
  - docs
  - packages/*
  - examples/*
  - test/**/*
catalog:
  '@clack/prompts': ^0.11.0
  '@types/react': 18.2.47
  '@types/react-dom': ^18.3.5
  consola: ^3.4.2
  next: latest
  react: ^18.3.1
  react-dom: ^18.3.1
  unconfig: ^7.3.2
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    '@antfu/ni': ^24.2.0
    '@types/yargs': ^17.0.33
    bumpp: ^10.1.0
    dotenv: ^16.4.7
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    nano-spawn: ^0.2.0
    nanospinner: ^1.2.2
    simple-git-hooks: ^2.11.1
    tsup: ^0.0.0
    tsx: ^4.19.3
    typescript: ^5.8.2
    vite: ^6.2.2
    yargs: ^17.7.2
  inlined:
    '@antfu/utils': ^9.1.0
  testing:
    vitest: ^3.0.9
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
