import fs from 'node:fs'

export function uniq<T>(array: T[]): T[] {
  return [...new Set([...array])]
}

export function m2fi(mod?: string | boolean): string {
  return mod !== 'env'
    ? mod === 'dotenv' ? 'env.vault' : `env.${mod}`
    : mod
}
export function write(filepath: string, parsed = {}): void {
  const contents = Object.entries(parsed)
    .map(([key, value]) => `${key}=${value}`)
  const content = [
    '# This file is generated by lnv command',
    '# DO NOT ATTEMPT TO EDIT THIS FILE',
    contents.join('\n'),
  ].join('\n')
  fs.writeFileSync(filepath, content, 'utf-8')
}

export function parseCommandString(command: string): string[] {
  if (typeof command !== 'string') {
    throw new TypeError(`The command must be a string: ${String(command)}.`)
  }

  const trimmedCommand = command.trim()
  if (trimmedCommand === '') {
    return []
  }

  const tokens: string[] = []
  for (const token of trimmedCommand.split(/ +/g)) {
    // Allow spaces to be escaped by a backslash if not meant as a delimiter
    const previousToken = tokens.at(-1)
    if (previousToken && previousToken.endsWith('\\')) {
      // Merge previous token with current one
      tokens[tokens.length - 1] = `${previousToken.slice(0, -1)} ${token}`
    }
    else {
      tokens.push(token)
    }
  }

  return tokens
}
